// flow-typed signature: e5d7ba9fe423dc4d9053086a9433e86e
// flow-typed version: <<STUB>>/commander_v^3.0.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'commander'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'commander' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'commander/index' {
  declare module.exports: $Exports<'commander'>;
}
declare module 'commander/index.js' {
  declare module.exports: $Exports<'commander'>;
}
