export const keyMap = {
  8: 'backspace',
  9: 'tab',
  13: 'enter',
  16: 'shift',
  17: 'ctrl',
  18: 'alt',
  19: 'pause_break',
  20: 'caps_lock',
  27: 'escape',
  32: 'space',
  33: 'page_up',
  34: 'page_down',
  35: 'end',
  36: 'home',
  37: 'left_arrow',
  38: 'up_arrow',
  39: 'right_arrow',
  40: 'down_arrow',
  45: 'insert',
  46: 'delete',
  48: '0',
  49: '1',
  50: '2',
  51: '3',
  52: '4',
  53: '5',
  54: '6',
  55: '7',
  56: '8',
  57: '9',
  65: 'a',
  66: 'b',
  67: 'c',
  68: 'd',
  69: 'e',
  70: 'f',
  71: 'g',
  72: 'h',
  73: 'i',
  74: 'j',
  75: 'k',
  76: 'l',
  77: 'm',
  78: 'n',
  79: 'o',
  80: 'p',
  81: 'q',
  82: 'r',
  83: 's',
  84: 't',
  85: 'u',
  86: 'v',
  87: 'w',
  88: 'x',
  89: 'y',
  90: 'z',
  91: 'left_window_key',
  92: 'right_window_key',
  93: 'select_key',
  96: 'numpad_0',
  97: 'numpad_1',
  98: 'numpad_2',
  99: 'numpad_3',
  100: 'numpad_4',
  101: 'numpad_5',
  102: 'numpad_6',
  103: 'numpad_7',
  104: 'numpad_8',
  105: 'numpad_9',
  106: 'multiply',
  107: 'add',
  109: 'subtract',
  110: 'decimal_point',
  111: 'divide',
  112: 'f1',
  113: 'f2',
  114: 'f3',
  115: 'f4',
  116: 'f5',
  117: 'f6',
  118: 'f7',
  119: 'f8',
  120: 'f9',
  121: 'f10',
  122: 'f11',
  123: 'f12',
  144: 'num_lock',
  145: 'scroll_lock',
  186: 'semi_colon',
  187: 'equal_sign',
  188: 'comma',
  189: 'dash',
  190: 'period',
  191: 'forward_slash',
  192: 'grave_accent',
  219: 'open_bracket',
  220: 'back_slash',
  221: 'close_braket',
  222: 'single_quote',
};

export const EMPTY = 'CADMUS/EMPTY';
export const INSERT_CHAR = 'CADMUS/ADD_CHAR';
export const INSERT_SPACE = 'CADMUS/INSERT_SPACE';
export const INSERT_ENTER = 'CADMUS/INSERT_ENTER';
export const REMOVE_CHAR = 'CADMUS/REMOVE_CHAR';
export const MOVE_CURSOR = 'CADMUS/MOVE_CURSOR';

const empty = (e) => ({
  type: EMPTY,
});

const insertChar = (e) => ({
  type: INSERT_CHAR,
  payload: e.key,
});

const insertSpace = (e) => ({
  type: INSERT_SPACE,
});

const insertEnter = (e) => ({
  type: INSERT_ENTER,
});

const removeChar = (e) => ({
  type: REMOVE_CHAR,
});

const moveCursor = (e) => ({
  type: MOVE_CURSOR,
  payload: e.key,
});

export const actionStorage = {
  0: (e) => insertChar(e),
  1: (e) => insertChar(e),
  2: (e) => insertChar(e),
  3: (e) => insertChar(e),
  4: (e) => insertChar(e),
  5: (e) => insertChar(e),
  6: (e) => insertChar(e),
  7: (e) => insertChar(e),
  8: (e) => insertChar(e),
  9: (e) => insertChar(e),
  backspace: (e) => removeChar(e),
  tab: (e) => empty(e),
  enter: (e) => insertEnter(e),
  shift: (e) => empty(e),
  ctrl: (e) => empty(e),
  alt: (e) => empty(e),
  pause_break: (e) => empty(e),
  caps_lock: (e) => empty(e),
  escape: (e) => empty(e),
  space: (e) => insertSpace(e),
  page_up: (e) => empty(e),
  page_down: (e) => empty(e),
  end: (e) => empty(e),
  home: (e) => empty(e),
  left_arrow: (e) => moveCursor(e),
  up_arrow: (e) => moveCursor(e),
  right_arrow: (e) => moveCursor(e),
  down_arrow: (e) => moveCursor(e),
  insert: (e) => insertSpace(e),
  delete: (e) => removeChar(e),
  a: (e) => insertChar(e),
  b: (e) => insertChar(e),
  c: (e) => insertChar(e),
  d: (e) => insertChar(e),
  e: (e) => insertChar(e),
  f: (e) => insertChar(e),
  g: (e) => insertChar(e),
  h: (e) => insertChar(e),
  i: (e) => insertChar(e),
  j: (e) => insertChar(e),
  k: (e) => insertChar(e),
  l: (e) => insertChar(e),
  m: (e) => insertChar(e),
  n: (e) => insertChar(e),
  o: (e) => insertChar(e),
  p: (e) => insertChar(e),
  q: (e) => insertChar(e),
  r: (e) => insertChar(e),
  s: (e) => insertChar(e),
  t: (e) => insertChar(e),
  u: (e) => insertChar(e),
  v: (e) => insertChar(e),
  w: (e) => insertChar(e),
  x: (e) => insertChar(e),
  y: (e) => insertChar(e),
  z: (e) => insertChar(e),
  left_window_key: (e) => empty(e),
  right_window_key: (e) => empty(e),
  select_key: (e) => empty(e),
  numpad_0: (e) => insertChar(e),
  numpad_1: (e) => insertChar(e),
  numpad_2: (e) => insertChar(e),
  numpad_3: (e) => insertChar(e),
  numpad_4: (e) => insertChar(e),
  numpad_5: (e) => insertChar(e),
  numpad_6: (e) => insertChar(e),
  numpad_7: (e) => insertChar(e),
  numpad_8: (e) => insertChar(e),
  numpad_9: (e) => insertChar(e),
  multiply: (e) => insertChar(e),
  add: (e) => insertChar(e),
  subtract: (e) => insertChar(e),
  decimal_point: (e) => insertChar(e),
  divide: (e) => insertChar(e),
  f1: (e) => empty(e),
  f2: (e) => empty(e),
  f3: (e) => empty(e),
  f4: (e) => empty(e),
  f5: (e) => empty(e),
  f6: (e) => empty(e),
  f7: (e) => empty(e),
  f8: (e) => empty(e),
  f9: (e) => empty(e),
  f10: (e) => empty(e),
  f11: (e) => empty(e),
  f12: (e) => empty(e),
  num_lock: (e) => empty(e),
  scroll_lock: (e) => empty(e),
  semi_colon: (e) => insertChar(e),
  equal_sign: (e) => insertChar(e),
  comma: (e) => insertChar(e),
  dash: (e) => insertChar(e),
  period: (e) => insertChar(e),
  forward_slash: (e) => insertChar(e),
  grave_accent: (e) => insertChar(e),
  open_bracket: (e) => insertChar(e),
  back_slash: (e) => insertChar(e),
  close_braket: (e) => insertChar(e),
  single_quote: (e) => insertChar(e),
};

export default function type(event) {
  return actionStorage[keyMap[event.code]](event);
}
